### ISSUE TITLE
Is it necessary to run ffmpeg process all the time?

### ISSUE THREAD

**Issue by tssk** [mozilla-iot/onvif-adapter#16]
Why not to start the ffmpeg process only when you actually want to see the video stream?

**Comment by mrstegeman** [comment]
The adapter has no way of knowing when a user is accessing the stream, so the only other way around running ffmpeg all the time would be to have a start/stop transcoding action (button).

Just for background info, the adapter tells the gateway about a new resource (the stream). The gateway then handles the connection.

**Comment by tssk** [comment]
Seems to me that opening the "stream" view is clear indication that user wants to see the stream. But if it is not possible to pass this information to adapter to start ffmpeg process then I undestand the current solution.

Thanks for explanantion.

**Comment by mrstegeman** [comment]
Although not a perfect solution, #19 will at least prevent the system from having to transcode everything at all times.

**Comment by tssk** [comment]
Big thanks for implementing this! It work just fine.

If I could I would suggest that maybe having only one button as toggle on/off might be more userfriendly. But this works just fine.

**Comment by mrstegeman** [comment]
Good call, I should have done that in the first place. That's now available in 0.2.1.
