### ISSUE TITLE
Select secondary / alternative transmission in Onvif plugin

### ISSUE THREAD

**Issue by afloresd** [mozilla-iot/onvif-adapter#24]
Hi,

I am completely new in this world of IoT and especially in Mozilla-IoT, the truth is that it is not precisely a problem, but a question because I was fascinated by streaming using a raspberry with mozilla webthings.

Is it possible to select the "alternative streaming" of an Onvif camera? I have a Dahua PC-HFW1230S camera, I tried to adjust the streaming quality as you indicated with the settings of the next thread

https://github.com/mozilla-iot/onvif-adapter/issues/12

But it has not worked, the main streaming itself is very heavy apparently, because it generates a lot of lag the video (let's agree that in my country 800K for streaming is very high: P), and I have observed that it is because it takes the resolution set in the camera to take the captures and transmit the video. Unfortunately, in the main streaming the minimum resolution is HD and it would be ideal to be able to configure the alternative transmission (which I always use in CIF quality and the device supports it only in secondary streaming).

Of course I appreciate your help and if you could guide me in what I should learn in a basic way to "not ask nonsense that are very obvious"

Greetings from Chile,

Alvaro.

**Comment by mrstegeman** [comment]
v0.3.0 is out now with a new "Profile" property, as well as a "High Quality" property. Hopefully those help!
