### ISSUE TITLE
Things screen failed to find onvif device

### ISSUE THREAD

**Issue by kisekitw** [mozilla-iot/onvif-adapter#5]
The camera is Pi camera made ONVIF compatible using https://github.com/BreeeZe/rpos.
After completing the installation guide, the camera seems work, I can view the stream by VLC(play rtsp://10.192.248.231:8554/h264).
When setting onvif-adapter, new devices auto-pupulated in the devices list, but Things screen didn't find anything, even manully input url (http://10.192.248.231:8081/onvif/device_service).

Thank you!

**Comment by mrstegeman** [comment]
This is actually an issue with the `rpos` library. See #4
