### ISSUE TITLE
foscam

### ISSUE THREAD

**Issue by eanmikale** [mozilla-iot/onvif-adapter#6]
Hi! We are having issues pulling up video on the gateway. We are able to connect it via app and can detect via gateway a video screen appears without video. 

using Foscam Camera, and Aeotec Dongle, with Firefox ESR Browser.

**Comment by mrstegeman** [comment]
Sorry to hear things aren't working properly.

1. Have you tried with another browser, i.e. the latest Firefox or Chrome releases?
2. Can you attach the log file from your gateway? You can get it from the UI via _Settings -> Developer -> View Logs_. The `run-app.log.*` file with the latest date should be sufficient.
3. Are there any errors in the browser's Javascript console? You can access that by pressing F12.
